name: wallpaper_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  wallpaper_manager_flutter: ^1.0.1
  path_provider: ^2.1.5
  dio: ^5.9.0
  http: ^1.5.0
  permission_handler: ^12.0.1
  image_gallery_saver_plus: ^4.0.1
  google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
